services:
  - type: web
    name: pdf-converter
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main_simple:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
    healthCheckPath: /health 